### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by 6Pinecones** [johnhungerford/mlca-advanced-python#1]
Hello, this is a test issue.

Edit: test

**Comment by johnhungerford** [comment]
Hi Ronan,

I'm writing this to make sure you receive notifications of our github conversations in your email and give you your next assignment while I wait to get access to google classroom.

This week I would like you to work your way through the eight tasks detailed below. They will introduce you to the development workflow we'll be using for the rest of the year. It's okay if you run into trouble with any of the steps. Just create another comment in this thread letting me know where you got stuck, and we can talk through it here (be sure to copy and paste any unexpected outputs or error messages you encounter into your comments). Also feel free to add any questions here, like if you are curious why I'm asking you to do something, want to know how something works, or any other reason.

1. Respond to this message, confirming that you received it. (Just add a comment below)
2. Set up `ssh` with github to allow you to push code to any repo you have access rights to:
    - Delete the folder you cloned from your fork of this repository. I've decided not to use github forks, as it unnecessarily complicates things. Instead of pushing your code to your own fork and merging them from there, I've added you as collaborators to this repository so that you can push code directly to a branch and merge to master from there.
    - Watch the following video and follow the instructions to get ssh set up: https://www.youtube.com/watch?v=a-zX_qc2S-M. `ssh` is a tool that allows a secure connection to a remote computer using public-key cryptography to keep all transferred information private from anyone snooping on the connection. This requires generating what's called a "key pair" consisting of two keys (files containing a string of randomly generated data used in the encryption/decryption processes). The "private key" is like your password: it must be kept secured on your computer and not shared with anyone. The "public key" can be given to anyone or any computer you want to communicate with. Secure connections are established via a "handshake" process between the remote computer using your public key and your own computer using your private key. Once your private key is set up on your computer and you have given your public key to github, you'll be able to push code and interact with github from your  command line without continually providing your username and password.
    - Once you've set up ssh, use ssh to clone this original repository: Navigate to https://github.com/johnhungerford/mlca-advanced-python, click the `Code` dropdown, click the `ssh` tab, copy the url that shows up there, and run `git clone [url]` on the command line in the directory where you keep your code.
3. Set up your development environment
    - On the command line, navigate to the cloned repository (run `cd mlca-advanced-python`) and run `scripts\set_env.bat`. Let me know if you see any error messages. After this runs you should see `.venv` to the left of the prompt in the command line.
    - This script does three things: 1) it tells python to treat your `mlca-advanced-python` directory as a project root so that the `import` statements in the python scripts work properly. 2) it creates a "virtual environment," which forces python to work from within the project directory: any libraries or dependencies you install will only install for the virtual environment and won't produce any conflicts with other projects you have on your computer. (It's always a good practice to do all your python work within a virtual environments.) 3) It installs all the python packages needed for our class.
4. Accept my invitation to be a collaborator: 
    - You should receive a notification in your email about the invitation with a link to accept it. Click the link. If you did not receive any email, go to: https://github.com/notifications.
    - This will be necessary for you to push your work to the repo.
5. Create a branch for your work
    - Run `git checkout -b ronan-assignments` -- this will create a new branch called "ronan-assignments" and switch to it (`checkout` changes branches, and the `-b` option will create the branch if it doesn't exist). Any work you do will be saved to this new branch.
6. Take a stab at a challenge problem:
    - The problems are defined in the `algorithms` directory, but I have made a copy of the ones I want you to work on in directory titled `ronan_solutions`. Start with `ronan_solutions\most_common_element_impl.py`.
    - Your task is to implement the function defined at the top of the file. The docstring below the function describes what that function is supposed to do. Executing the file will run tests on the function to see if it does it what it's supposed to. Confirm that this works by running: `python ronan_solutions\most_common_element.impl.py`. It should output `Failed!` a bunch of times. (If you see an error that it can't find a module, that means your dev environment hasn't been set up correctly.)
    - Replace the `pass` keyword with an implementation of behavior specified in the docstring. When you think you did it right, run the tests again (`python ronan_solutions\most_common_element_impl.py`). If you did it correctly you should see `Passed!` instead of `Failed!` You may pass some of the tests and fail others. Take a look at the error messages to see what's going wrong.
    - Don't worry about passing all the tests if you find the problem difficult. I'm mostly interested in your getting used to using git and github.
7. Commit your solution:
    - Saving your work to the repository's git history involves two steps: 1) "staging" your changes and 2) "committing" them. Staging changes allows you to choose which changes you want to include in your commits, and committing is what writes them to the history.
    - Before doing anything, run `git status`. This command should output your branch name, and then show any files you have edited in *red*. This is all of your *unstaged* work. If you run `git diff`, you will see all of the changes you have made to each edited file. Your updated lines of code will appear in green with a `+` next to them. The old lines of code will appear in red with a `-` next to them. The *only* files that should show up under the `status` and `diff` commands should be your own problem solutions. If you see any other files in red, this means you have accidentally edited them. To undo any accidental work, run `git checkout -- [filename]`. This will return that file to the most recent staged or committed state. Be sure not to do that to the file you're working on though, or you will use your work!
    - Run `git add .` (include the period) this will "stage" any changes you've made to the repository. The period stands for "current directory," so `git add .` means stage everything in the current directory. You can also run `git add [filename]` to stage a single edited file, or `git add [filename1] [filename2] ...` to stage multiple files.
    - Run `git status`. You should now see your edited files listed in *green*. Green filenames represent *staged* files. Note that if you run `git diff` you will no longer see any of your edits. The `diff` command only compares unstaged work with staged or committed work.
    - Run `git commit -m "My first commit"`. This will commit (permanently save) your staged changed, along with a message. Note that the `commit` command never takes files or directories as arguments like the `add` command does. `git commit` will always commit every staged change.
    - Run `git status` again. You should now see no red or green filenames. Instead it should display your branch name along with the message "nothing to commit, working tree clean". Similarly, `git diff` should not show anything.
    - Run `git log`. This should display a list of commits. At the top of the list you should see your message ("My first commit"). You can scroll through the commit log using up and down arrows. To exit the log, type `q`.
8. Push your work (i.e., upload it to github)
    - Run `git push --set-upstream origin ronan-assignments`. This will upload your branch to the online github repository. The `--set-upstream` option is necessary to tell `git` to connect your local branch to the original remote repository (`origin`) using the same branch name as your local branch (`ronan-assignments`). After you run this full command the first time, you will only have to run `git push` to upload new commits to github.
    - Confirm that your changes are on github by navigating to the repository (https://github.com/johnhungerford/mlca-advanced-python) and clicking the dropdown menu titled `main` above the files display on the left-hand side. You should now see your branch. If you click on it, it will take you to the version of the repository in your branch. Click on the link to the directory `ronan_solutions` and then click on `most_common_element_impl.py`. You should then see the version of the file that you committed.

**Comment by johnhungerford** [comment]
@6Pinecones (testing if calling you out will generate an email notification)

**Comment by 6Pinecones** [comment]
Message and email both received.
