### ISSUE TITLE
Week 3 Classwork

### ISSUE THREAD

**Issue by johnhungerford** [johnhungerford/mlca-advanced-python#10]
@Arcaeyn @6Pinecones 

For this week, our goal is to get all your current challenge problem solutions passing their tests and getting the physics engine up to speed.

1. I've made some updates to the test cases and the test runner in the main branch, so again remerge main to your working branches:
    - Make sure you commit any changes to your current branch (`git add .`, `git commit -m '[commit message here]'`)
    - `git checkout main`
    - `git pull`
    - `git checkout [your-name]-assignments`
    - `git merge main [your-name]-assignments -m 'Pulling latest changes to main'`
2. Work on your assignments
    - Make sure you run `scripts\set_env.bat` on the command line when start up a new CMD session. If there are any complaints about `pip` not being found, run `python -m pip install -r requirements.txt`
    - Make sure all your tests pass for the three challenge problems in your solutions folder. Remember to run tests you just execute the following: `python [your-name]_solutions\[problem-name]_impl.py` to run tests.
    - Marshall (@Arcaeyn): make the updates we discussed to `PhysicsObject`. If you do this quickly, take a look at `PhysicsSystemRenderer` and see if you can make sense of it.
    - Ronan (@6Pinecones): please implement `PhysicsSystem`
3. IMPORTANT: get started on this stuff sooner rather than later and respond to this issue with questions or to let me know that you've finished.
    - Make sure you are in YOUR branch (use `git status` or `git branch` to check). If you are in `main` or any other branch, use `git checkout [your-name]-assignments` to change branches.
    - Commit and push your code frequently (think of this as "saving"): `git add .`, `git commit -m '[very short message about what changes you made]'`, `git push`

**Comment by Arcaeyn** [comment]
I accidently wrote a really bad physics renderer, but currently the physics renderer has `pass` in most of the methods. Do you want me to code those functions?

**Comment by johnhungerford** [comment]
@Arcaeyn if you want to get started on the renderer, go ahead and start implementing the methods in `Ascii1DPhysicsSystemRenderer` -- the `PhysicsSystemRenderer` is only an "abstract class" which is implemented in other classes that inherit it. Be sure to read all the doc strings.

I would start with `render_current_frame()`, which should just output a single line representing the physics system. Then you could go through the others one by one. But to answer your question, yes, all the methods will need to be implemented for the class to run.

**Comment by johnhungerford** [comment]
@Arcaeyn I just took a look at your `PhysicsObject` implementation and noticed that your `update_pos` method is defined as `self.pos_x += self.vel_x`. This would mean that to get the next position, you simply add the velocity to it. But isn't the next position going to depend on how much time has passed? This is why the `update_pos` method should take a parameter `delta_t` (which means "change in time"). How would you change your definition if you update the method signature to:

```python
def update_pos(self, delta_t: float):
     ...
```

**Comment by johnhungerford** [comment]
@Arcaeyn I added a couple tests to `main` for `PhysicsObject`. These tests are using a tradition testing framework (`pytest`) instead of the runner I wrote for your challenge problems. To run the tests, make sure you've set up your development environment and then run `pytest` or `python -m pytest`. Of course you have to merge my changes in `main` into your branch. Do you remember how to do that? (If not, see above.)

**Comment by Arcaeyn** [comment]
Okay

**Comment by Arcaeyn** [comment]
I  have this
```python
def update_pos(self, delta_t):
            self.pos_x += self.vel_x * delta_t
```

**Comment by johnhungerford** [comment]
@Arcaeyn looks good -- can you pull my tests in and run them?

**Comment by 6Pinecones** [comment]
Hello! 
I have two questions. 

-If I modified the file physics_object.py (since it is in physics_engine, and not ronan-assignments) and push, will this affect anything, or is it okay to have done some work in this file?

-For physics_system, aside from the method for an update, should the set of objects be local or listed in test cases outside the class? I understand I will have to account for the objects within the class, but essentially, where should they be defined?

**Comment by Arcaeyn** [comment]
Both the tests passed. I'll start working on the renderer.

**Comment by johnhungerford** [comment]
@Arcaeyn great! Note that the renderer is going to depend on `PhysicsSystem` methods that don't exist yet because Ronan hasn't implemented it. I suggest you start by assuming that `PhysicsSystem` has a constructor that accepts a list of `PhysicsObject`s and a method `update_state(self, delta_t)` that updates the internal state of all objects within it after time `delta_t`.

@6Pinecones 
1. It's okay to do work on files in the `physics_engine` directory. Your branch `ronan-assignments` actually has nothing to do with which files in the repository you are working on, it is just a logical distinction between the changes *you* make to the whole repo and the changes *other* people make.
2.  For `PhysicsSystem`, the objects should be passed to the constructor (i.e., the `__init__()` method as parameters. So when anyone creates a `PhysicsSystem` instance, they will have to have already created all the `PhysicsObject`s that will belong to it.
