### ISSUE TITLE
Week 2 Classwork

### ISSUE THREAD

**Issue by johnhungerford** [johnhungerford/mlca-advanced-python#8]
@Arcaeyn @6Pinecones 

For this week I want you to do the following:

1. I have pushed some updates to the `main` branch, please merge them back into your own working branches.
  - First make sure your local main branch is up to date with what's on github.: a) Run `git checkout main`; b) confirm you are in main by running `git status` or `git branch`; c) run `git pull`
  - Now merge your local main branch into your local working branch: a) Run `git checkout [your-name]-assignments`; b) confirm you are in your branch with `git status` or `git branch`;  c) run `git merge master [your-name]-assignments -m 'Merged latest changes'`; d) confirm your changes are committed by running `git log` -- you should see 'Merged latest changes' at the top of the log.

2. You now have three files in your "solutions" folder, including the `most_common_elements` one from last week. Do the two you haven't done yet. (Ronan, see if you can also get your `most_common_elements` solution to work). If you run into trouble or have any questions, please post about it here -- just make sure you push your code.

3. You'll also see I have stubbed out the physics engine classes we discussed today in class. See if you can define appropriate `__init__` methods, along with any methods and fields we discussed (I captured most of what we said in the docstrings). Remember, @Arcaeyn you are implementing `PhysicsObject`, and @6Pinecones you're doing `PhysicsSystem`. Again, reply here if you have any questions.

**Comment by Arcaeyn** [comment]
I hate to have to bring this up but when running `git merge master marshall-assignments -m 'Merged latest changes'` I get the following error:
```
C:\Users\marsh\code\mlca-advanced-python>git merge master marshall-assignments -m 'Merged latest changes'
merge: master - not something we can merge
```

Do I need to give git some extra perms?

**Comment by johnhungerford** [comment]
@Arcaeyn my mistake: use `main` not `master`. (I’m used to the main branch being titled “master”)

**Comment by Arcaeyn** [comment]
Okay

**Comment by Arcaeyn** [comment]
Another error while pushing code, (also cant figure out how to run the tests to see if my code works):

```
C:\Users\marsh\code\mlca-advanced-python>git push
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.36 KiB | 465.00 KiB/s, done.
Total 8 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Required status check "test" is expected. Waiting on code owner review from johnhungerford.
To github.com:johnhungerford/mlca-advanced-python.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:johnhungerford/mlca-advanced-python.git'
```

**Comment by johnhungerford** [comment]
@Arcaeyn 

It looks from what you pasted that you are trying to push from the `main` branch. You should be doing all your working in `marshall-assignments`. I suggest you run:

```
git checkout marshall-assignments
git merge main marshall-assignments
git push
```

We can go through it in class tomorrow.

**Comment by Arcaeyn** [comment]
Oh okay
